language: python
branches:
  only:
  - master
  - develop
  - stable
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
   pip install -r test_requirements.txt
script:
  - pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)
